name: Build and publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :generator-web-cli:runShadow --args='-o output/ --server --client -v 1.20.4 -v 1.20.3 -v 1.20.2 -v 1.20.1 -v 1.20 -v 1.19.4 -v 1.19.3 -v 1.19.2 -v 1.19.1 -v 1.19 -v 1.18.2 -v 1.18.1 -v 1.18 -v 1.17.1 -v 1.17 -v 1.16.5 -v 1.16.4 -v 1.16.3 -v 1.16.2 -v 1.16.1 -v 1.15.2 -v 1.15.1 -v 1.15 -v 1.14.4 -v 1.14.3 -v 1.14.2 -v 1.14.1 -v 1.14 -v 1.13.2 -v 1.13.1 -v 1.13 -v 1.12.2 -v 1.12.1 -v 1.12 -v 1.11.2 -v 1.11.1 -v 1.11 -v 1.10.2 -v 1.10 -v 1.9.4 -v 1.9.2 -v 1.9 -v 1.8.8'
      - name: Commit and push changes
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: build
          folder: ./generator/web-cli/output